Ich verstehe folgende Kommandos:

Allgemein
!ls help: Diese Liste

Video
!ls random: Zufälliges Let's Shoot Video in den Channel posten
!ls search ar15 schalldämpfer: Suche ein Video im Kanal von Let's Shoot und poste maximal 3 Ergebnisse
!ls last: Poste das letzte veröffentlichte Video von Let's Shoot

Radio
!ls stations: Liste alle Radiostationen auf, die im Radio-Channel gepspielt werden können
!ls station [Nummer der Station]: Wechsele nach dem Ende des aktuell gespielten Videos zur angegebenen Radio-Station
!ls playurl [die URL zu einem YouTube Video]: Spielt das angegebene Video als nächstes
!ls skip: Die aktuelle Wiedergabe stoppen und das nächste Video abspielen